name             'storage'
maintainer       'Ron Ellis'
maintainer_email 'rone@benetech.org'
license          'All rights reserved'
description      'Installs/Configures storage'
long_description 'Installs/Configures storage'
version          '0.3.152'

depends 'zfs_linux', '~> 2.0.1'
depends 'aws', '~> 2.4.0'